.github/scripts/add-nu-dependencies.sh
.github/workflows/main.yml
Cargo.toml
README.md

this PR fixes the version of `nu-plugin` and `nu-protocol` to the latest stable release on *crates.io*: 0.83.1.
it also fixes the version of the plugin itself to 0.1.0 and updates the README.

use the latest stable revision of Nushell dependencies

---

README.md
src/app.rs
src/config/mod.rs
src/config/parsing.rs
src/navigation.rs
src/tui.rs

- fbcb3ab: *allow the Config to be cloned*
- 9be5ceb: *give a &Key to transition_state*
- ce401b7: *implement Default for Mode and State*
- 0770cca: *refactor the state initialization in `from_value`*
- ae3ed68: *fix overflow panic when moving in the data*
- df49a86: *make `State::from_value` public to super*
- 4c26453: *derive PartialEq and Debug for the whole config*

adds tests

---

README.md
examples/configuration/themes/dark.nuon
src/config/mod.rs
src/tui.rs

this PR adds colors to the three line segments
- the name, data and shapes column have now different colors in the "table" layout
- the "name: (shape) data" lines of the "compact" layout have different colors, for the name, the shape and the data, just as in "table" layout but compacted
these colors can be changed through config :ok_hand:

give different colors to table columns

---

src/event.rs

this PR avoids crashing when losing / gaining focus and pasting into the application.

do not do anything with "exotic" events

---

src/handler.rs
src/nu/cell_path.rs
src/nu/value.rs
src/ui.rs

should close #12 and more
i think all the following should render as tables inside `explore`
- :heavy_check_mark: a normal full table
```nushell
> [{a: "foo", b: 1}, {a: "bar", b: 2}]
╭───┬─────┬───╮
│ # │  a  │ b │
├───┼─────┼───┤
│ 0 │ foo │ 1 │
│ 1 │ bar │ 2 │
╰───┴─────┴───╯
```
- :x: the same table with mixed columns
```nushell
> [{a: "foo", b: 1}, {b: 2, a: "bar"}]
╭───┬─────┬───╮
│ # │  a  │ b │
├───┼─────┼───┤
│ 0 │ foo │ 1 │
│ 1 │ bar │ 2 │
╰───┴─────┴───╯
```
- :x: `null` in the first column
```nushell
> [{a: null, b: 1}, {a: "bar", b: 2}]
╭───┬─────┬───╮
│ # │  a  │ b │
├───┼─────┼───┤
│ 0 │     │ 1 │
│ 1 │ bar │ 2 │
╰───┴─────┴───╯
```
- :x: `null` in the second column
```nushell
> [{a: "foo", b: 1}, {a: "bar", b: null}]
╭───┬─────┬───╮
│ # │  a  │ b │
├───┼─────┼───┤
│ 0 │ …
```

detect and render more "fuzzy" tables

---

examples/config/default.nuon
src/config/mod.rs
src/handler.rs
src/lib.rs
src/nu/value.rs
src/ui.rs

this PR adds the ability to tranpose the current view, if it's a table or a record, just as the built-in `transpose` command does.
the default binding is `t`.
the transposition is an *involution*, i.e. it is its self inverse, meaning that applying the tranposition twice give you back the original data.

add support from table / record transposition

---

rust-toolchain.toml

this is to make sure the local version of Rust and the remote one in the CI are in sync and avoid CIs such as the one of https://github.com/amtoine/nu_plugin_explore/pull/30 to fail where the local one is working correctly.

fix the rust toolchain version

---

Cargo.toml
src/edit.rs
src/ui.rs

this has the benefit of simplifying the code on the side of `nu_plugin_explore` a bit :ok_hand:

bump ratatui to 0.26.1

---

build.nu

this is a minor fix in case there might be a `nu` binary in the `PATH` on top of the system `nu` one, with different versions.
this PR makes sure the one used inside the Nupm build script is the same as the currently running Nushell instance.

use current Nushell executable in the build script

---

Cargo.toml

Copied ver batim from sigoden/aichat#264.
- Identical bug: sigoden/aichat#257
- Request for docs: crossterm-rs/crossterm#849
- Similar bug: https://github.com/crossterm-rs/crossterm/issues/644#issuecomment-1073114710
- Source bug: crossterm-rs/crossterm#500
- Fix (enabled in this PR): crossterm-rs/crossterm#735
```
│hread '<unnamed>' panicked at src/event.rs:46:45:                                                             │
│o events available: Custom { kind: Other, error: "Failed to initialize input reader" }                        │
```
In case of regression:
```diff
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│key                             bfield …
```

Fix panic on Mac from `crossterm::event::poll`

---

.github/workflows/main.yml
.github/workflows/scripts/check-cargo-lock.sh
Cargo.lock
Makefile

- use the Makefile rules
- check the `Cargo.lock` file (see how the CI is failing because it's not up to date)
- update `Cargo.lock` (see how the CI becomes green again)

check `Cargo.lock` in the CI

---

examples/config/default.nuon
src/config/mod.rs
src/nu/value.rs
src/ui.rs

this PR
- makes it that `nu::value::is_table` returns a `nu::value::Table` variant which hold more information about why the value is not a table
- adds a warning banner at the bottom to indicate the user why they are seeing a list of records
- adds a bunch of new tests for `is_table` for the new table variants
- make the colors of the warning banner configurable
> **Important**
> this will only work with #41, this can be achieved by running
> ```bash
> git merge bump-set_foreground
> ```
> on top of this commit

add a warning when a near-table is detected

---

src/app.rs
src/handler.rs
src/navigation.rs
src/ui.rs

this PR adds the following support
- in NORMAL mode, enter a number _n_ and then press `config.keybindings.navigation.down` to go down _n_ rows
- in NORMAL mode, enter a number _n_ and then press `config.keybindings.navigation.up` to go up _n_ rows
- in NORMAL mode, enter a number _n_ and then press _g_ to jump to line number _n_
- in NORMAL mode, press _control + d_ to jump half a page down (half page size is hardcoded for now)
- in NORMAL mode, press _control + u_ to jump half a page up (half page size is hardcoded for now)
- in NORMAL mode, press _g_ to jump to the top
- in NORMAL mode, press _G_ to jump to the bottom

add support for motion repetition

---

src/ui.rs

in large data, getting close to the bottom would make the last element "lift off" the bottom of the frame, leaving empty lines below it even though there is enough lines to fill the entire frame...
this PR constrains the "tops" to be less than `nb_lines - height`, forcing the last element of the data to always be at the bottom if there are enough lines to fill the frame.

make sure the bottom of the data stays at the bottom

---

Cargo.lock
Cargo.toml
nupm.nuon

related to
- nushell/nushell#12448
this PR on the Nushell side just landed, it's time to bump `nu_plugin_explore`
- point to nushell/nushell@c06ef201b72b3cbe901820417106b7d65c6f01e1
- bump the plugin to version `0.92.3-c06ef201b72b3cbe901820417106b7d65c6f01e1`

bump to `0.92.3-c06ef201b72b3cbe901820417106b7d65c6f01e1`

---

Cargo.lock
Cargo.toml
nupm.nuon

makes `nu_plugin_explore` on par with nushell/nushell@2595f31541554c6d8602ebebc9dffbc4dd29dd89

bump to `0.92.3-2595f31541554c6d8602ebebc9dffbc4dd29dd89`

---

Cargo.lock
Cargo.toml

remove `console` from the dependencies

---

Cargo.lock
Cargo.toml
nupm.nuon
src/nu/value.rs
src/tui/event.rs

Fix panics when sending to the TUI channel.
Because failing to send just means the other end hung up, we don't really need to do anything special. It's totally expected that the other side will hang up eventually. It's best for us to just break out of the loop.
This also updates nushell to a revision I have right now that fixes local socket, but this should probably be changed on release.

Fix TUI channel panics

---

README.md
scripts/deps.nu

might help for things like https://github.com/amtoine/nu_plugin_explore/issues/64

add a helper module to install Nushell dependencies

---

Cargo.lock
Cargo.toml
nupm.nuon
src/edit.rs
src/tui/mod.rs
src/ui.rs

with minor updates to edit.rs, upgrade cargo dependencies
The updates to edit.rs were required for the upgrade to 0.102 of nu-protocol
I was having some issues with versions of `mio` pulled in by ratatui and crossterm, so I upgraded their dependencies as well as other cargo dependencies, the other changes to files are just updating ratatui's deprecated methods.

bump to 0.102.0 
